baseURL = 'https://1pathplanningzzj.github.io/'
languageCode = 'zh-cn'
title = 'æˆ‘çš„ä¸ªäººä¸»é¡µ'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  disableScrollToTop = false
  hidemeta = false
  showtoc = true
  tocopen = false

  [params.homeInfoParams]
    Title = "ä½ å¥½ ğŸ‘‹"
    Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººä¸»é¡µ"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:zijianzhang821@gmail.com"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/1pathplanningzzj"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "zijian"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "research"
    name = "ç ”ç©¶æ–¹å‘"
    url = "/research/"
    weight = 20

  [[menu.main]]
    identifier = "posts"
    name = "çŸ¥è¯†åº“"
    url = "/posts/"
    weight = 30

  [[menu.main]]
    identifier = "archives"
    name = "å½’æ¡£"
    url = "/archives/"
    weight = 40

  [[menu.main]]
    identifier = "search"
    name = "æœç´¢"
    url = "/search/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
